version: '3'
services:
  fdk-harvester-bff:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff:test
    environment:
      - CONCEPT_HARVESTER_BASE_URL=http://fdk-services-mock:8080
      - DATASET_HARVESTER_BASE_URL=http://fdk-services-mock:8080
      - INFORMATION_MODEL_HARVESTER_BASE_URL=http://fdk-services-mock:8080
      - ORGANIZATION_CATALOGUE_BASE_URI=http://fdk-services-mock:8080
      - REFERENCE_DATA_BASE_URI=http://fdk-services-mock:8080
      - DATA_SERVICE_HARVESTER_BASE_URL=http://fdk-services-mock:8080
    ports:
      - "8080:8080"
    depends_on:
      - "fdk-services-mock"

  fdk-services-mock:
      image: rodolpheche/wiremock
      ports:
        - "8081:8080"
      volumes:
        - ./mock/mappings:/home/wiremock/mappings
