version: '3'
services:
  fdk-harvester-bff:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff:test
    environment:
      - HOST=${HOST}
      - HOST_PORT=${HOST_PORT}
      - PUBLISHER_URL=${PUBLISHER_URL}
      - PASSWORD=${PASSWORD}
    ports:
      - "8080:${HOST_PORT}"
    depends_on:
      - "fuseki"

  fuseki:
      image: stain/jena-fuseki
      environment:
        - TDB=${TDB}
        - ADMIN_PASSWORD=${PASSWORD}
        - FUSEKI_DATASET_1=${DATASET_1}
      ports:
        - "3030:${FUSEKI_PORT}"
