name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Deploy to production environment on merge to master branch
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      # Setup gcloud CLI

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
      # Configure docker to use the gcloud command-line tool as a credential helper

      - run: gcloud auth configure-docker

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      - name: Install dependencies
        run: |
          pip install nox==2019.11.9
          pip install poetry==1.0.5

      - name: Test with nox
        run: nox

      - name: Tag and publish docker image to Google Cloud
        run: |
          docker tag eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff:test eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff:$GITHUB_SHA
          docker tag eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff:test eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff:latest
          docker rmi eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff:test
          docker -- push eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
            helm fetch --untar --untardir ./helm fdk/fdk-harvester-bff
            helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/fdk-harvester-bff:$GITHUB_SHA" -f ./helm/fdk-harvester-bff/values/prod.yaml ./helm/fdk-harvester-bff/ > ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
          project_id: digdir-fdk-prod
          location_zone: europe-north1-a
          cluster_name: digdir-fdk-prod

      - name: Deploy to prod
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: fdk-harvester-bff | Environment: prod'
          fields: commit,author,workflow,message
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Trigger deploy to demo
        uses: peter-evans/repository-dispatch@master
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: deploy-demo
          client-payload: '{"sha": "${{ github.sha }}"}'
